# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_as_hex <- function(sig) {
  assert_class(sig, "eth_signature")
  return(invisible(NULL))
}

assert_return_as_hex <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_EthSigner__initialize <- function(private_key) {
  assert_any_of(
    private_key,
    function(.x) {
      assert_scalar_character(.x)
    },
    function(.x) {
      assert_raw(.x)
      assert_length(.x, 32L)
    }
  )
  return(invisible(NULL))
}

assert_return_EthSigner__initialize <- function(value) {
  assert_class(value, "EthSigner")
  return(value)
}

assert_args_EthSigner__sign_digest <- function(digest32) {
  assert_raw(digest32)
  assert_length(digest32, 32L)
  return(invisible(NULL))
}

assert_return_EthSigner__sign_digest <- function(value) {
  assert_class(value, "eth_signature")
  return(value)
}

assert_args_EthSigner__sign_typed_data <- function(domain, primary_type, types, message) {
  assert_list(domain)
  assert_scalar_character(primary_type)
  assert_list(types)
  assert_list(message)
  return(invisible(NULL))
}

assert_return_EthSigner__sign_typed_data <- function(value) {
  assert_class(value, "eth_signature")
  return(value)
}

assert_args_EthSigner__sign_message <- function(text) {
  assert_scalar_character(text)
  return(invisible(NULL))
}

assert_return_EthSigner__sign_message <- function(value) {
  assert_class(value, "eth_signature")
  return(value)
}

assert_args_eth_signer <- function(private_key) {
  assert_any_of(
    private_key,
    function(.x) {
      assert_scalar_character(.x)
    },
    function(.x) {
      assert_raw(.x)
      assert_length(.x, 32L)
    }
  )
  return(invisible(NULL))
}

assert_return_eth_signer <- function(value) {
  assert_class(value, "EthSigner")
  return(value)
}

assert_return_eth_signer_random <- function(value) {
  assert_class(value, "EthSigner")
  return(value)
}

assert_type_eth_signature <- function(value) {
  assert_class(value, "eth_signature")
  return(invisible(value))
}

